config/routes.rb
Rails.application.routes.draw do

  # we use customised controller, instead of the controller provided by the gem
  use_doorkeeper # do
  #   controllers authorizations: 'custom_authorizations'
  # end

  resource :ldap_login, only: [:new, :create]

  devise_for :users, controllers: {
               sessions: 'users/sessions'
             }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      # another api routes
      get '/me' => "credentials#me"
    end
  end

  root to: 'doorkeeper/applications#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ldap.rb
require 'net/ldap'

class Ldap
  def initialize
  end

  def get_ldap_response(ldap)
    msg = "Response Code: #{ ldap.get_operation_result.code }, Message: #{ ldap.get_operation_result.message }"

    raise msg unless ldap.get_operation_result.code == 0
  end

  def authenticate_ldap(login, password)
    raise ArgumentError, 'password is nil' if login.blank? or password.blank?

    require 'net/ldap'
    ldap      = Net::LDAP.new
    ldap.host = 'salcam2' # LDAP_CONFIG['host']
    ldap.port = 389 # LDAP_CONFIG['port']
    ldap.auth "uid=#{login},ou=People,dc=salltd,dc=co,dc=uk", password

    bound = ldap.bind
    if bound
      base = "uid=#{login}, ou=People,dc=salltd, dc=co, dc=uk"
      result_attrs = ['sAMAccountName', 'displayName', 'mail']
      found = ldap.search(base: base,
                          return_results: true,
                          attributes: result_attrs)
      get_ldap_response(ldap) # raise error if no success

      found.first[:mail].first
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :login

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :access_grants, class_name: "Doorkeeper::AccessGrant",
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens, class_name: "Doorkeeper::AccessToken",
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  validate :user_has_downcased_email

  def user_has_downcased_email
    if email.downcase != email
      errors.add(:email, "You must use downcased email")
    end
  end

  def admin?
    admin_users = ['jacek.podkanski@conceptlifesciences.com',
                         'jon.adams@conceptlifesciences.com']

    admin = true if admin_users.select{ |ue| email == ue }.any?
    admin
  end
end

app/controllers/api/v1/api_controller.rb
module Api::V1
  class ApiController < ::ApplicationController
    private
    def current_resource_owner
      User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
    end
  end
end

app/controllers/api/v1/credentials_controller.rb
module Api::V1
  class CredentialsController < ApiController
    before_action :doorkeeper_authorize!
    respond_to     :json

    def me
      respond_with current_resource_owner
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ldap_logins_controller.rb
class LdapLoginsController < Doorkeeper::AuthorizationsController
  # ApplicationController

  # finding that took couple of hours
  before_action :authenticate_resource_owner!, except: [:new, :create]
  respond_to :json, only: :create

  def new
  end

  # if you get errors here it might be because the client doesn't have
  # the correct credentials, in one case copying the credentials in
  # config/secrets.yml to the production section has fixed the problem
  def create
    login = params['login']
    password  = params['password']
    client_id = params[:client_id]

    authenticated = Ldap.new.authenticate_ldap(login, password).to_s.downcase

    @user = User.where(email: authenticated).first
    unless @user
      # password is not used because we use OAUTH authentication
      # but still we set it on semi-random hash
      @user = User.new(email: authenticated,
                       password: Digest::MD5.new.update(Time.now.ctime).hexdigest)
      @user.save
    end

    session[:user_id] = @user.id

    unless authenticated.blank?
      if client_id
        client_app = Doorkeeper::Application.where(uid: client_id).first

        if client_app
          code = Doorkeeper::AccessToken.find_or_create_for(client_app,
                                                            @user.id,
                                                            nil,
                                                            7200,
                                                            true )

          grant = Doorkeeper::AccessGrant.create(resource_owner_id: @user.id,
                                                 application_id: client_app.id,
                                                 token: code.token,
                                                 expires_in: 600,
                                                 redirect_uri: client_app.redirect_uri,
                                                 scopes: nil)
          # why do I have to update the token?
          grant.update(token: code.token)

          redirect_to (client_app.redirect_uri +
                       '?' +
                       { code: code.token,
                         state: params[:state]
                       }.to_query)
        else
          logger.error "problem with the client app credentials, make sure you app secrets uuid and secret match the values stored in the OAuth2 Provider admin panel"
          super
        end
      else
        # no action dispatch cookie
        logger.error "client_id was blank #{client_id}"
        super
      end
    else
      logger.info "authentication failed for: #{login}"
      # not authenticated
      super
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  def create
    login = params['user']['login']
    password  = params['user']['password']

    authenticated = Ldap.new.authenticate_ldap(login, password).to_s.downcase

    @user = User.where(email: authenticated).first
    unless @user
      # TODO
      # we need to create admin users from the console, because all other users
      # passwords are are set to the same string, random hash would be better
      @user = User.new(email: authenticated, password: 'not-applicable')
      @user.save
    end
    sign_in @user
    session[:user_id] = @user.id

    redirect_to root_path
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ldap_logins_helper.rb
module LdapLoginsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthorisationServer - Admin Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "doorkeeper/admin/application" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
      <%= link_to t('doorkeeper.layouts.admin.nav.oauth2_provider'), oauth_applications_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == oauth_applications_path %>">
            <%= link_to t('doorkeeper.layouts.admin.nav.applications'), oauth_applications_path, class: 'nav-link' %>
          </li>
          <% if respond_to?(:root_path) %>
            <li class="nav-item">
              <%= link_to t('doorkeeper.layouts.admin.nav.home'), root_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>

      </div>
    </nav>

    <div class="doorkeeper-admin container">
      <%- if flash[:notice].present? %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end -%>

      <%= yield %>

      <% if current_user %>
        <p>
          <%= link_to "Sign out", destroy_user_session_path, class: 'btn btn-warning float-lg-right', method: :delete %>
        </p>
        <% end %>
    </div>
  </body>
</html>

app/views/layouts/authorization.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authorisation Server - User Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "doorkeeper/admin/application" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
      <div class="navbar-brand">
        User Login
      </div>

      <div class="collapse navbar-collapse">


      </div>
    </nav>

    <div class="doorkeeper-admin container">
      <%- if flash[:notice].present? %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end -%>

      <%= yield %>

      <% if current_user %>
        <p>
          <%= link_to "Sign out", destroy_user_session_path, class: 'btn btn-warning float-lg-right', method: :delete %>
        </p>
      <% end %>
    </div>
  </body>
</html>

app/views/ldap_logins/new.html.erb
<h2>User Log in</h2>

<%= form_tag(ldap_login_path) do %>
  <% [:client_id, :state].each do |k| %>
    <%= hidden_field_tag k, params[k] %>
  <% end %>

  <div class="field">
    <%= label_tag(:login, "Login") %><br>
    <%= text_field_tag(:login) %>
  </div>

  <div class="field">
    <%= label_tag(:password, "Password") %><br>
    <%= password_field_tag(:password) %>
  </div>
  <br>
  <div class="actions">
    <%= submit_tag("Log in", class: 'btn btn-primary ') %>
  </div>

<% end %>